- .circleci/config.yml
- interfaces/WebexAdapter.test.js
- package-lock.json
- package.json
rebased of the PR https://github.com/webex/component-adapter-interfaces/pull/2
> Jest Setup

- src/ActivitiesAdapter.js
- src/MeetingsAdapter.js
- src/PeopleAdapter.js
- src/RoomsAdapter.js
Type definitions in `MeetingsAdapter` updates:
* Added `MediaStream`
* Added `MediaStreamTrack`
* Update to `MeetingControl`
* Added `MeeetingControlDisplay`
> Meeting controls typedef

- src/MeetingsAdapter.js
- src/MeetingsAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-111743
> Add LeaveMeeting Method

- package-lock.json
- package.json
This gets rid of most vulnerabilities in this repository.
> Updating to latest Dev Dependencies

- src/MembershipsAdapter.js
- src/MembershipsAdapter.test.js
- src/index.js
Added the interface of MembershipAdapter
> feat(membership): add membership adapter

- src/MembershipsAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-154254
> docs(MembershipsAdapter): add member definition

- package.json
- src/ActivitiesAdapter.test.js
- src/MembershipsAdapter.test.js
- src/PeopleAdapter.test.js
- src/RoomsAdapter.test.js
- src/WebexAdapter.test.js
All tests in the repository follow the same format now.
> test: standardize test format

- src/MembershipsAdapter.js
Add `isInMeeting` property to member
> feat(member): update properties

- src/MembershipsAdapter.js
Changed the interface definition to return an array of members.
> refactor(MembershipsAdapter): change return type of getMembersFromDestination to observable of member array

- src/MembershipsAdapter.js
- src/OrganizationsAdapter.js
- src/OrganizationsAdapter.test.js
- src/PeopleAdapter.js
- src/RoomsAdapter.js
- src/index.js
Adds a new adapter to represent organizations in Webex.
> Organizations interface

- src/MembershipsAdapter.js
Add the host property for the Member object.
> feat(MembershipsAdapter): add the boolean property "host" for the Member object

- src/MembershipsAdapter.js
Add guest property for the Member interface.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-222984
> feat(MembershipsAdapter): add boolean property "guest" to the Member interface

- src/MeetingsAdapter.js
- src/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223893
> feat(MeetingsAdapter): add status for meeting

- src/MeetingsAdapter.js
fix(MeetingsAdapter): change statuses for meeting
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-225968
> fix(MeetingsAdapter): change states for meeting

- src/WebexAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-229275
This PR is about adding the connect() and disconnect() functions in the WebexAdapter interface.
> feat(WebexAdapter): add connect() and disconnect() functions

- .github/workflows/dispatch-new-version-event.yml
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227495
> build(workflow): dispatch event for new version

- src/MeetingsAdapter.js
This enum stored possible values for audio/video permissions.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-238895
> feat(MeetingsAdapter): add MediaPermissions enum

- src/MeetingsAdapter.js
Add new fields in the meeting object:
- cameraID
- microphoneID
- speakerID
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-249010
> feat(MeetingsAdapter): add devices ids in meeting object

- package-lock.json
- package.json
Updating semantic-release to latest:
* semantic-release v18
* @semantic-release/git v10
* @semantic-release/changelog v6
> build(DevDependencies): update semantic-release to v18

- .circleci/config.yml
- .nvmrc
> ci(node): use LTS/Fermium

- src/MeetingsAdapter.js
Add "joining" state in meeting states.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-277304
> feat(MeetingsAdapter): add "lobby" state in meeting states

- src/PeopleAdapter.js
- src/PeopleAdapter.test.js
add a getPeopleList method to People Adapter to get list of people by search query
> feat(PeopleAdapter): add getPeopleList method

- src/ActivitiesAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-314570
> feat(ActivitiesAdapter): add 'attachments' and 'cards' properties to Activity object

- src/MembershipsAdapter.js
- src/MembershipsAdapter.test.js
`addRoomMember` and `removeRoomMember` methods
> feat(MembershipsAdapter): add methods addRoomMember and removeRoomMember

- src/webexcalling/src/IMetricsAdapter.ts
> fix: package for release

- src/webexcalling/src/ISearchContactsAdapter.ts
Added comment for interface method
> Fix(SpeedDial): added comment for interface method

- src/webexcalling/src/ISearchContactsAdapter.ts
Renamed function to force build publish
> Fix(SpeedDial): rename get contact function for interface

- src/webexcalling/src/ISearchContactsAdapter.ts
feat(callhistory): Added contact search interfaces method
> feat(callhistory): Added contact search interfaces method

- src/webexcalling/src/ISpeedDialsAdapter.ts
Description:  Added ContactId property to ISpeedDialRecord
> fix(contactId): added contactId

- src/webexcalling/src/ISpeedDialsAdapter.ts
Description:  Changed the speed dial's update parameter
> fix(sdUpdateParam): changed parameter

- src/webexcalling/src/ICallForwardAdapter.ts
- src/webexcalling/src/index.ts
Description:  Added types for call forward settings
> fix(callForwardSettings): call forward types

- src/webexcalling/src/ISpeedDialsAdapter.ts
Added isOutlookDeleted type to ISpeedDialRecord
> fix(speeDialType): added speedDial Type

- src/webexcalling/src/ICallForwardAdapter.ts
Added the types for callForward
> Call forward

- src/webexcalling/src/Logger.ts
- src/webexcalling/src/index.ts
Description:  Added a new component called Logger with download logs logic.
> fix(DownloadLogs): Implemented Download Logs Feature

- src/webexcalling/src/ICallHistoryAdapter.ts
Changed the field name from data to readStatusMessage
> fix(callHistory): updated the field name

- src/webexcalling/src/ICallHistoryAdapter.ts
Description:  Added Multi-Line data types
> Adding Multi-Line data types

- src/webexcalling/src/IVoicemailAdapter.ts
added the method for VM transcription
> fix(Ivoicemail): added the methods for transcription

- src/webexcalling/src/ICallHistoryAdapter.ts
Description:  Added data types for delete call log feature
> fix(ICallHistoryAdapter): Added delete call log data types

- src/webexcalling/src/ICallForwardAdapter.ts
Description:  Added CxEssential data types in the ICallForwardAdapter.ts file
> fix(ICallForwardAdapter): Added CxEssential types
